### ISSUE TITLE
v1.02 INI file shall be reused in v1.03 installation

### ISSUE THREAD

**Issue by sorintopan** [OPCFoundation/UA-LDS#13]
An installation of 1.03 over an existing LDS 1.02 shall reuse the existing ualds.ini file and import the certificate paths and the registered servers

Basically there should be preserved the following ini keys/sections:
TrustListPath, IssuerPath, RejectedPath, RegisteredServers

**Comment by dk2129** [comment]
Since products may rely on them I suggest that TrustListPath, IssuerPath, and RejectedPath are maintained even for new installations.

**Comment by erhardgrishaber** [comment]
Fixed in LDS v.1.03.370
