### ISSUE TITLE
OPC UA LDS Service is removed when installing a second product containing the UA LDS 1.03 merge module (on same host )

### ISSUE THREAD

**Issue by FMartens-ATS** [OPCFoundation/UA-LDS#18]
I have created 2 installers (for different products) that include the ‘OPC_UA_Local_Discovery_Server_1.03.msm’ merge module (from opc-ua-local-discovery-server-1.03.367-mergemodule-20170518.zip). When I install the first product, the ‘OPCF Bonjour Service’ and ‘OPC UA Local Discovery Service’ are installed and started. When I run the second installer, the ‘OPC UA Local Discovery Service’ is removed from the services but the files are still present on the file system. The ‘ualds.exe’ process is also missing in the task manager.

Here are some details from the installer log for the second application, the lines below do not appear in the installer log of the first application.

Line 9375: MSI (s) (60:00) [10:21:52:823]: Executing op: RegisterSharedComponentProvider(,,File=opcualds.exe.4E6EDC62C0B245CF831D3C5D4806F990,Component={F2957780-1BDE-4A54-AD41-864FD1BC51FE},ComponentVersion=1.3.341.0,ProductCode={AD3D9D38-66A7-4010-BA66-DFABF66A81B3},ProductVersion=1.5.17166,PatchSize=0,PatchAttributes=0,PatchSequence=0,SharedComponent=0,IsFullFile=0)

Line 12145: CustomAction Action_RegisterUaldsService.4E6EDC62C0B245CF831D3C5D4806F990 returned actual error code 1 but will be translated to success due to continue marking

 
The UA LDS installs and updates fine when using the MSI (as chained MSI) instead of the merge module.

Did someone else notice the same behavior too?

I've posted the same issue on the opc foundation website but I have been informed that this would be the best place to report the issue.

**Comment by opcfoundation-org** [comment]
May be the same issue: 
https://github.com/OPCFoundation/UA-LDS/issues/21

**Comment by erhardgrishaber** [comment]
Fixed in LDS v.1.03.370
