### ISSUE TITLE
Adding UA-LDS endpoints to local discovery service

### ISSUE THREAD

**Issue by Stasik0** [OPCFoundation/UA-LDS#19]
Hi,

is the server supposed to list the discovered UA-LDS server via its LDS? Currently it seems to me that it is doing it only the other way round (i.e. registrations to LDS are broadcastet via mDNS).

**Comment by randy-armstrong** [comment]
The latter. The LDS incorporates the mDNS code and announces all server which register with it.

**Comment by Stasik0** [comment]
but not the other way around, correct? Why not?

**Comment by Stasik0** [comment]
ping?

**Comment by randy-armstrong** [comment]
i don't understand what you mean by the 'other way around'.
the server generally does not care about other servers registered with the LDS.

**Comment by Stasik0** [comment]
I would like server that broadcast mDNS information to appear on the old-school LDS

**Comment by randy-armstrong** [comment]
The LDS-ME has two methods FindServers and FindServersOnNetwork.

FindServers returns the Servers that have explicitly registered with the LDS.
FindServersOnNetwork returns all Servers which have announced themselves via mDNS.
UaExpert should support both (or it will support both in the near future - you need to contact Unified support).
