### ISSUE TITLE
Prevent huge logfile 

### ISSUE THREAD

**Issue by cacamille3** [OPCFoundation/UA-LDS#2]
I have an instance of an UA-LDS on my PC provided by a third party OPC UA Server.
It created a 2Gb log file on my computer.
It will be great to limit the max size that could be set in configuration file LogFileSize parameter
Currently only a check that the LogFileSize is greater than 0 is done...

In this log file I only have one error present A LOT of time : 

> Ignored invalid message security mode ','.

**Comment by erhardgrishaber** [comment]
In older versions of the LDS (1.02) it is not possible to set the log size.
In the latest version of LDS v1.03.341 it is possible to set the log size in the configuration file (ualds.ini). It will backup the old file and create a new logfile:
[Log]
# Log System: syslog (system log), file (custom log file)
LogSystem = file
# LogFile: path to logfile. This is only required for LogSystem=file.
LogFile = C:\ProgramData\OPC Foundation\UA\Discovery\opcualds.log
# Log Level: error, warn, info, debug
LogLevel = debug
#Maximum logfile size in MB. This is only required for LogSystem=file.
LogFileSize = 100

**Comment by cacamille3** [comment]
I know, but what will be interresting is to have a hard encoded value in the code let say 200MB, that will prevent config file with too large LogFileSize value...
Then you could set uaIds.ini 
`#Maximum logfile size in MB. This is only required for LogSystem=file (maxValue = 200, default = 100)`

**Comment by sorintopan** [comment]
This would a too pessimistic scenario we would not handle for the moment. Anyway persons modifying the ini files should have awareness about the effects of their changes.
