### ISSUE TITLE
LDS 1.03 with corrupted configuration file

### ISSUE THREAD

**Issue by GMarquardt** [OPCFoundation/UA-LDS#22]
In some rare circumstances the configuration file of LDS is corrupted. It contains the following 10 lines.

> [Log]
> #Maximum logfile size in MB. This is only required for LogSystem=file.
> LogFileSize = 100
> 
> [General]
> []
> SemaphoreFilePath = C:\Program Files (x86)\Common Files\OPC Foundation\UA\Discovery\bin\opcualds.exe
> [PKI]
> [CertificateInfo]
> 

I inspected the source code and I suspect that while shutting down, LDS damages its configuration file.
In main() ualds_settings_close() is called which flushes the configuration data and then frees the memory for configuration data. While this happens in another thread some OPC UA server registers and new memory may be allocated for configuration data. Finally the new configuration is flushed to file. This may lead to the 10 lines of garbage in the configuration file.
Please verify my theory. I have no other idea how the ini file gets its content.

**Comment by K47S** [comment]
We also have this issue from time to time.

**Comment by erhardgrishaber** [comment]
Fixed in LDS v.1.03.370

**Comment by JochenKalmbach** [comment]
We also had seen this issues. This issue arises if there is a multi-threaded access to the ini file. From my point of view, it is a big mistake to store the registration of the OCP UA server into the configuration file! This is the main reason for the problems. Why is it needed to use ONE file for configuration and the SAME file for runtime-data??? This is normally a no-go. So please separate the configuration from the runtime-data. This would be one step into the right direction. Of course, the mutli-threaded issue also should be solved....
