### ISSUE TITLE
Failed to open Windows store

### ISSUE THREAD

**Issue by kapsl** [OPCFoundation/UA-LDS#23]
Hi,
since weeks we are struggling getting the local discovery server running. We do it under windows. And every time I try to connect to the discovery server, the certificate lands under rejected. I copy it in the trusted folder, but the next retry - again, a certificate in the rejected folder is created (with exactly same filesize etc. so its the same certificate).

A log output is that it failed, to open the windows certificate store. I have no more ideas... Could anybody help?

lg Manu

**Comment by K47S** [comment]
Could you provide a copy of your UALDS.ini?

My idea is that the ApplicationCerts of your OPC UA application arent valid. Have you tried to register with a OPC UA Demo Server?

**Comment by kapsl** [comment]
I'm currently using the ProSys SDK and the certificate is loaded like in their sample application...

Hi the ualds.ini in OPC Foundation/Config is
# UA Local Discovery Server configuration file.

# This file must be encoded in UTF-8.

# * Comments start with a leading #

# * Comments and empty lines are ignored, but will be preserved

# * Section names, keys and values are case sensitive

# * Keys must not contain whitespaces

# * Values may contain whitespaces, but leading and trailing whitespace will be removed

# * Values can be quoted to preserve whitepaces: e.g. " leading space"

# * Quotes inside quotes can be escaped by a backslash: e.g. "bla\"foo"

# * Array values are possible: e.g. Foo[2], where Foo has subkeys "x" and "y"

#     Foo/size = 2

#     Foo/0/x = 5

#     Foo/0/y = 6

#     Foo/1/x = 7

#     Foo/1/y = 8

 

[General]

# The OPCUA application uri used by the LDS.

ServerUri = urn:[gethostname]:UALocalDiscoveryServer

# maximum age of registered server entries before they expire in seconds. (Default=600)

ExpirationMaxAge = 600

# AllowLocalRegistration: (default=no) this will disable certificate trust checks for connections comming from

# localhost. Note that this is a security risk. Only enable this feature if you are aware of the full implications.

#AllowLocalRegistration = yes

# Endpoint configuration

# Number of available endpoints

Endpoints/size = 1

Endpoints/0/Url = opc.tcp://[gethostname]:4840

Endpoints/0/SecurityPolicies = SecurityPolicy_None, SecurityPolicy_Basic128Rsa15, SecurityPolicy_Basic256

 

[SecurityPolicy_None]

Url = http://opcfoundation.org/UA/SecurityPolicy#None

MessageSecurity = None

 

[SecurityPolicy_Basic128Rsa15]

Url = http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15

MessageSecurity = Sign, SignAndEncrypt

 

[SecurityPolicy_Basic256]

Url = http://opcfoundation.org/UA/SecurityPolicy#Basic256

MessageSecurity = Sign, SignAndEncrypt

 

[CertificateInfo]

# Certificate information for creating self-signed certificates on startup

# This is only used if no certificate exists in the configured path.

# On machine name change, the own certificate should be re-created by uninstalling/reinstalling LDS OR by deleting the actual certificate and restarting the service.

CommonName = UA Local Discovery Server

Organization = OPC Foundation

OrganizationUnit =

Locality = 16101 N. 82nd Street, Scottsdale

State = Arizona

Country = US

 

[PKI]

#Certificate Store Path

CertificateStorePath = C:\ProgramData\OPC Foundation\UA\pki

# Maximum number of rejected certificates. This prevents malicious programs from filling up available disk space by

# calling OpenSecureChannel with different certificates.

MaxRejectedCertificates = 50

# MaxAge for rejected certificates: Rejected certificates will be deleted automatically after this time in days.

MaxAgeRejectedCertificates = 1

# Windows certificate store (only for backward compatibility to old LDS store)

# Enable certificate validation using the given windows certificate store (yes / no)

Win32StoreCheck = yes

 

[Log]

# Log System: syslog (system log), file (custom log file)

LogSystem = file

# LogFile: path to logfile. This is only required for LogSystem=file.

LogFile = C:\ProgramData\OPC Foundation\UA\Discovery\opcualds.log

# Log Level: error, warn, info, debug

LogLevel = debug

# Maximum logfile size in MB. This is only required for LogSystem=file.

LogFileSize = 100

# Activate UaStack trace: off, error, warn, info, debug

StackTrace = off

 

[RegisteredServers]

# This section contains all registered server entries. The first entry is always the LDS itself.

# Servers/size is the number of entries.

# Servers/0/ServerUri is the first entry.

# Servers/1/ServerUri is the second entry and so on.

# For each ServerUri there must exist a section with the same name

# which contains the detailed information of the server entry.

Servers/size = 1

Servers/0/ServerUri = urn:[gethostname]:UALocalDiscoveryServer

 

[urn:[gethostname]:UALocalDiscoveryServer]

# The Local Discovery Server entry. This is always the first entry.

# ProductUri: The ProductUri from the RegisteredServer structure as defined in the

# OPC UA Specification - Part 4, Chapter 5.4.4 RegisterServer

# ServerNames Array: Array of LocalizedText entries

# ServerType: 0=Server, 1=Client, 2=ClientAndServer, 3=DiscoveryServer

# GatewayServerUri:

# DiscoveryUrls: Array of Discovery Urls

# SemaphoreFilePath: The semaphore file makes this entry a static entry. This entry will only be removed when the configured

#  semaphore file does not exist anymore.

# UpdateTime: time_t when the server entry was updated the last time. Only used for dynamic registration when SemaphoreFilePath is empty.

ProductUri = http://opcfoundation.org/UA/LocalDiscoveryServer

ServerNames/size = 1

ServerNames/0/Locale = en-US

ServerNames/0/Text = UA Local Discovery Server

# ServerType: 0=Server, 1=Client, 2=ClientAndServer, 3=DiscoveryServer

ServerType = 3

GatewayServerUri = (null)

DiscoveryUrls/size = 1

DiscoveryUrls/0/Url = opc.tcp://[gethostname]

SemaphoreFilePath = C:\Program Files\Common Files\OPC Foundation\UA\Discovery\bin\opcualds.exe

MdnsServerName = UA Local Discovery Server on [gethostname]

ServerCapabilities/size = 1

ServerCapabilities/0/Capability = LDS

 

[Zeroconf]

# Enable Zeroconf functionality in the LDS (default=yes)

EnableZeroconf = yes

# Interval in which the LDS checks the registrations at the local Zeroconf service (minimum/default: 5)

RegistrationInterval = 5

In OPC Foundation/UA/Discovery its 
# UA Local Discovery Server configuration file.
# This file must be encoded in UTF-8.
# * Comments start with a leading #
# * Comments and empty lines are ignored, but will be preserved
# * Section names, keys and values are case sensitive
# * Keys must not contain whitespaces
# * Values may contain whitespaces, but leading and trailing whitespace will be removed
# * Values can be quoted to preserve whitepaces: e.g. " leading space"
# * Quotes inside quotes can be escaped by a backslash: e.g. "bla\"foo"
# * Array values are possible: e.g. Foo[2], where Foo has subkeys "x" and "y"
#     Foo/size = 2
#     Foo/0/x = 5
#     Foo/0/y = 6
#     Foo/1/x = 7
#     Foo/1/y = 8

[General]
# The OPCUA application uri used by the LDS.
ServerUri = urn:[gethostname]:UALocalDiscoveryServer

# maximum age of registered server entries before they expire in seconds. (Default=600)
ExpirationMaxAge = 600

# AllowLocalRegistration: (default=no) this will disable certificate trust checks for connections comming from
# localhost. Note that this is a security risk. Only enable this feature if you are aware of the full implications.
#AllowLocalRegistration = yes

# Endpoint configuration
# Number of available endpoints
Endpoints/size = 1
Endpoints/0/Url = opc.tcp://[gethostname]:4840
Endpoints/0/SecurityPolicies = SecurityPolicy_None, SecurityPolicy_Basic128Rsa15, SecurityPolicy_Basic256

[SecurityPolicy_None]
Url = http://opcfoundation.org/UA/SecurityPolicy#None
MessageSecurity = None

[SecurityPolicy_Basic128Rsa15]
Url = http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
MessageSecurity = Sign, SignAndEncrypt

[SecurityPolicy_Basic256]
Url = http://opcfoundation.org/UA/SecurityPolicy#Basic256
MessageSecurity = Sign, SignAndEncrypt

[CertificateInfo]
# Certificate information for creating self-signed certificates on startup
# This is only used if no certificate exists in the configured path.
# On machine name change, the own certificate should be re-created by uninstalling/reinstalling LDS OR by deleting the actual certificate and restarting the service.
CommonName = UA Local Discovery Server
Organization = OPC Foundation
OrganizationUnit = 
Locality = 16101 N. 82nd Street, Scottsdale
State = Arizona
Country = US

[Log]
# Log System: syslog (system log), file (custom log file)
LogSystem = file
# LogFile: path to logfile. This is only required for LogSystem=file.
LogFile = C:\ProgramData\OPC Foundation\UA\Discovery\opcualds.log
# Log Level: error, warn, info, debug
LogLevel = debug
# Maximum logfile size in MB. This is only required for LogSystem=file.
LogFileSize = 100
# Activate UaStack trace: off, error, warn, info, debug
StackTrace = off

[RegisteredServers]
# This section contains all registered server entries. The first entry is always the LDS itself.
# Servers/size is the number of entries.
# Servers/0/ServerUri is the first entry.
# Servers/1/ServerUri is the second entry and so on.
# For each ServerUri there must exist a section with the same name
# which contains the detailed information of the server entry.
Servers/size = 1
Servers/0/ServerUri = urn:[gethostname]:UALocalDiscoveryServer
[urn:[gethostname]:UALocalDiscoveryServer]
# The Local Discovery Server entry. This is always the first entry.
# ProductUri: The ProductUri from the RegisteredServer structure as defined in the
# OPC UA Specification - Part 4, Chapter 5.4.4 RegisterServer
# ServerNames Array: Array of LocalizedText entries
# ServerType: 0=Server, 1=Client, 2=ClientAndServer, 3=DiscoveryServer
# GatewayServerUri:
# DiscoveryUrls: Array of Discovery Urls
# SemaphoreFilePath: The semaphore file makes this entry a static entry. This entry will only be removed when the configured
#  semaphore file does not exist anymore.
# UpdateTime: time_t when the server entry was updated the last time. Only used for dynamic registration when SemaphoreFilePath is empty.
ProductUri = http://opcfoundation.org/UA/LocalDiscoveryServer
ServerNames/size = 1
ServerNames/0/Locale = en-US
ServerNames/0/Text = UA Local Discovery Server
# ServerType: 0=Server, 1=Client, 2=ClientAndServer, 3=DiscoveryServer
ServerType = 3
GatewayServerUri = (null)
DiscoveryUrls/size = 1
DiscoveryUrls/0/Url = opc.tcp://[gethostname]
SemaphoreFilePath = C:\Program Files (x86)\Common Files\OPC Foundation\UA\Discovery\bin\opcualds.exe
MdnsServerName = UA Local Discovery Server on [gethostname]
ServerCapabilities/size = 1
ServerCapabilities/0/Capability = LDS
[Zeroconf]
# Enable Zeroconf functionality in the LDS (default=yes)
EnableZeroconf = yes
# Interval in which the LDS checks the registrations at the local Zeroconf service (minimum/default: 5)
RegistrationInterval = 5
[PKI]
CertificateStorePath = C:\ProgramData\OPC Foundation\UA\pki
MaxRejectedCertificates = 50
MaxAgeRejectedCertificates = 1
Win32StoreCheck = yes
