### ISSUE TITLE
No rolling file logs

### ISSUE THREAD

**Issue by K47S** [OPCFoundation/UA-LDS#24]
Hello,

for production use its not ideal to copy the whole log file to another logfile (Log_%Y-%m-%d_%H-%M-%S.log) when the maximum filesize is reached. 
This leads to the problem that the LDS possibly fills the whole system space with logs (see [#2](https://github.com/OPCFoundation/UA-LDS/issues/2))

Code:
[https://github.com/OPCFoundation/UA-LDS/blob/acd2a2023f3bb74cd5e5b2574dd5161bd7a54147/win32/log.c#L174](https://github.com/OPCFoundation/UA-LDS/blob/acd2a2023f3bb74cd5e5b2574dd5161bd7a54147/win32/log.c#L174)

Are there plans to implement rolling file logs?

**Comment by erhardgrishaber** [comment]
Fixed in LDS v.1.03.370
