### ISSUE TITLE
CertificateStorePath seems to be ignored

### ISSUE THREAD

**Issue by K47S** [OPCFoundation/UA-LDS#31]
The setting for CertificateStorePath seems to be ignored for trusted certs.
My setting:
CertificateStorePath = C:\ProgramData\OPC Foundation\UA\pki

LDS own cert ist stored correctly:
C:\ProgramData\OPC Foundation\UA\pki\own

Trusted certs will be stored in:
C:\ProgramData\OPC Foundation\UA\Discovery\pki\trusted

Maybe related to: [https://github.com/OPCFoundation/UA-LDS/blob/6bf1e4b292464102cd6bbd189270cf7da1761091/win32/certstore.c#L110](https://github.com/OPCFoundation/UA-LDS/blob/6bf1e4b292464102cd6bbd189270cf7da1761091/win32/certstore.c#L110)

**Comment by erhardgrishaber** [comment]
According to OPC-UA Spec Part 12 Table 48, the trusted certificates should be stored in <root>/trusted/certs, where <root> is %CommonApplicationData%\OPC Foundation\UA\pki
So it will look in C:\ProgramData\OPC Foundation\UA\pki\trusted\certs

If not found, it will look also in the default path used in LDS v1.02, whish is C:\ProgramData\OPC Foundation\UA\Discovery\pki\trusted\certs

The new version of LDS (that is about to be released) will also look in the value of TrustListPath key from ualds.ini configuration file. Also for backward compatibility.

The current version will not look in the custom path you specified.

**Comment by K47S** [comment]
Okay thanks for clarification.
