### ISSUE TITLE
LDS does not reject servers that register with an Invalid or Empty ProductURI

### ISSUE THREAD

**Issue by FredLoveless** [OPCFoundation/UA-LDS#34]
While working on a different issue with a customer using our server we discovered that we were not providing the ProductURI when we registered with the LDS. Customer had written a client that was failing discovery because of this empty filed.

If I understand the specification correctly this is a required field. I would like the LDS to reject registration with an error if possible.

As a side note, I tested 7 different UA Clients and none of them complained about the empty ProductURI. Client developers should take a look at their validation code as well.

**Comment by sorintopan** [comment]
Please provide the requirement you mentioned in the specification regarding the mandatory ProductURI.
Could not find in 1.03 spec.
