### ISSUE TITLE
Crashes and new Installation needed

### ISSUE THREAD

**Issue by kapsl** [OPCFoundation/UA-LDS#35]
Hi together,
we build an OPC UA Application that relies on a local discovery server. The server was running for eventually several days. And devices were continuosly registering / unregistering or just killed. 

We found that the discovery server crashes approximately twice a day and needs a restart. We couldn't track this back to any certain action we took, as always the same procedure was executed.

Once it happened, that the discovery server crashed, and couldn't start up again, because it said, that it couldn't load its own certificate. A restart of the computer didn't help. Finally we needed to re-install the LDS to get it back working :-( It seems like the crash somehow corrupted the certificates or configuration files or something...

Greets

**Comment by erhardgrishaber** [comment]
Can provide the UA-LDS version you are using ? If it is older than v1.03.370, please try to update and let me know if the crash is still reproducing.
