### ISSUE TITLE
"The installation of OPC UA Local Discovery Server 1.03.371.424 appears to have failed" when using MSI or EXE as prerequisite

### ISSUE THREAD

**Issue by FMartens-ATS** [OPCFoundation/UA-LDS#37]
A "The installation of OPC UA Local Discovery Server **1.03.371.424** appears to have failed" message is shown as soon as the OPC UA LDS 1.03.371.424 MSI (copied from SUPPORTDIR) or EXE prerequisite is executed by my windows installer. The prerequisite is started and the installer immidiately shows the warning message while the OPC UA LDS MSI/EXE continues execution.

I also have a prerequisiste using the OPC UA LDS 1.02 msi. That prerequisite installs fine and does not throw the warning. The controls in my installer are disabled and a progress bar runs while the 1.02 prerequisite runs. With the 1.03 prerequisite on the other hand, the progress bar in the main installer does not run and the warning message is shown.

I use the following condition for the UA LDS 1.03 prerquisite:
`<conditions>
		<condition Type="1" Comparison="2" Path="HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{7A4A8B23-8023-45B4-9857-3E95A74C5243}" FileName="" ReturnValue=""/>
	</conditions>
`

Various resources online state that the reason for the "The installation of OPC UA Local Discovery Server 1.03.371.424 appears to have failed" message is that the condition did not change:
https://community.flexerasoftware.com/showthread.php?192048-Prereq-install-says-it-fails-but-it-is-installed&p=451128#post451128

BTW: I noticed that I had to use a different  productcode for 1.03 because the product codes for 1.02 and 1.03 are not the same:
- OPC UA LDS 1.02: {B7D7491E-43FD-4E7A-96BC-7DBFBFAC3795}
- OPC UA LDS 1.03: {7A4A8B23-8023-45B4-9857-3E95A74C5243}

It there something I forgot to add to the condition of the UA LDS 1.03 prerequisite?

**Comment by erhardgrishaber** [comment]
In order to use the LDS in other installations, we recommend the MergeModule (msm).
To investigate the above problem, we need  some extra informations:
1)	Previous LDS installed versions (if there is installed).
2)	Details regarding the enviroment: OS version, other tools that use/include the LDS/BonjourService.
3)	Logging info from LDS installation (see MSI command logging).

**Comment by FMartens-ATS** [comment]
The mergemodule work but they are installed under our 'product code'.

1) There is no previous version installed.
2) Windows 8.1 Pro, no other tools that use the LDS. Not sure about BonjourService.
3) [ualds103.log](https://github.com/OPCFoundation/UA-LDS/files/1673577/ualds103.log)

**Comment by FMartens-ATS** [comment]
The installation starts and shows the following dialog:
![pending](https://user-images.githubusercontent.com/29632411/35513633-0dd3ec1c-0504-11e8-8ecd-808f032014b9.png)

Then I press 'Install' and the status changes: Extracting --> Installing --> Failing: 
![failed](https://user-images.githubusercontent.com/29632411/35513631-0d9736c8-0504-11e8-984a-6489446bb305.png)

The OPC UA LDS installer is still open and I can continue the installation. I can also continue the installation of my own product.

**Comment by FMartens-ATS** [comment]
This is when using the OPC UA LDS 1.02 MSI, the status remains 'installing' until the end of the MSI installation.
![opc_ua_lds_102](https://user-images.githubusercontent.com/29632411/35513965-0633c4ae-0505-11e8-9e78-5c3bd9912d6a.png)

There is no urgent need to for a 1.03 prerequisiste since the OPC UA LDS 1.02 prerequisite is working fine. I only wanted to report the change in behavior.

**Comment by FMartens-ATS** [comment]
Not sure if the following is an issue:
OPC UA Local Discovery Server 1.02.msi has a digital signature
OPC UA Local Discovery Server 1.03.371.424.msi is not digitally signed

**Comment by opcfoundation-org** [comment]
>> OPC UA Local Discovery Server 1.03.371.424.msi is not digitally signed

This statement does not appear to be true. I just downloaded the MSI and checked.

**Comment by FMartens-ATS** [comment]
Here is a little more logging or do you need the complete log?

MSI (c) (00:18) [19:59:46:191]: Note: 1: 1402 2: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer 3: 2 
MSI (c) (00:18) [19:59:46:191]: SOFTWARE RESTRICTION POLICY: Verifying package --> 'C:\Users\fmartens\AppData\Local\Temp\{E426AF6F-F602-4DAF-A504-D05FF48151B8}\OPC UA Local Discovery Server 1.03.msi' against software restriction policy
MSI (c) (00:18) [19:59:46:191]: Note: 1: 2262 2: DigitalSignature 3: -2147287038 
MSI (c) (00:18) [19:59:46:191]: SOFTWARE RESTRICTION POLICY: C:\Users\fmartens\AppData\Local\Temp\{E426AF6F-F602-4DAF-A504-D05FF48151B8}\OPC UA Local Discovery Server 1.03.msi is not digitally signed
MSI (c) (00:18) [19:59:46:193]: SOFTWARE RESTRICTION POLICY: C:\Users\fmartens\AppData\Local\Temp\{E426AF6F-F602-4DAF-A504-D05FF48151B8}\OPC UA Local Discovery Server 1.03.msi is permitted to run at the 'unrestricted' authorization level.

![image](https://user-images.githubusercontent.com/29632411/35750371-0cd70638-0855-11e8-95db-bcb9edc1ce6e.png)

The dialog above is presented when executing 'OPC UA Local Discovery Server 1.03.371.424.exe'

Not sure if I mentioned it before but I am installing on Windows 8.1 Pro 64-bit on a 64-bit platform.

**Comment by erhardgrishaber** [comment]
@FMartens-ATS : In the description you mentioned "using MSI or EXE ". There is no official released MSI file, only EXE. Do you have a *.msi file ?

**Comment by FMartens-ATS** [comment]
I know, I obtained when running the EXE. You are able to find the directory where the MSI is stored when  you run the EXE with verbose logging.

**Comment by rikku1004** [comment]
@erhardgrishaber : Hello.. I'am try to build the OPC UA LDS but i am encountering errors. is it possible if you can walk me through the steps?. I have no previous experience in implementing this kind of build.. Thanks!

**Comment by rikku1004** [comment]
@erhardgrishaber I also tried downloading the ms/zip and msm.. Can I plese ask for your help on how should I install it? thanks..

**Comment by rikku1004** [comment]
@erhardgrishaber Thanks for the quick reply.. As for the installation and build.. the outcome or output is the same right? actually I did both, but sadly I was not able to launch both.. as for the installation.. I downloaded the file from here: "https://opcfoundation.org/developer-tools/samples-and-tools-unified-architecture/local-discovery-server-lds/" I extracted the file file and installed it in my machine. what I did is I went to the bin folder and run the "Opc.Ua.DiscoveryServer" application, but there was no response. I was kinda expecting a window might pop up or anything but I didnt get any response. What Should I expect after the installation?

**Comment by erhardgrishaber** [comment]
The LDS is a service, so it does not have a "window". The binary file is in C:\Program Files (x86)\Common Files\OPC Foundation\UA\Discovery\bin\opcualds.exe
The "Opc.Ua.DiscoveryServer" file is obsolete and not used.
After installation it should start automatically. If you want you can stop the service adn start it as a console application by running the command "opcualds.exe -d" in a terminal.

**Comment by rikku1004** [comment]
@erhardgrishaber : I see.. So I've been assuming the wrong idea the whole time..
Thanks! I'll let you know about the progress..

**Comment by rikku1004** [comment]
@erhardgrishaber hello again, after I installation i tried starting and stopping the program but I am getting this error "'opcualds.exe' is not recognized as an internal or external command,
operable program or batch file."

**Comment by rikku1004** [comment]
@erhardgrishaber hello again. I have installed the OPCUA lds.. but I was unable to run it in the terminal as you said.. I'm getting this error.. C:\>opcualds.exe -d
'opcualds.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by erhardgrishaber** [comment]
@rikku1004 Can you run it as a Service (as it is intended) ?
![lds_service](https://user-images.githubusercontent.com/17177166/44645822-ae314380-a9e1-11e8-878f-ae073802b437.jpg)

**Comment by erhardgrishaber** [comment]
When running from Terminal, you need to be in the same folder as than executable !!! (C:\Program Files (x86)\Common Files\OPC Foundation\UA\Discovery\bin) and stop the service (otherwise there is a port conflict).

**Comment by erhardgrishaber** [comment]
A detailed description on how it should work is described in the OPC-UA Specification v1.03 (or v1.04) Part 12 (it can be downloaded from the official OPC foundation website). The basic idea is that OPC-UA Servers can register to a Local Discovery Server by calling "RegisterServer" or "RegisterServer2" (secured only, cerificates must be trusted) on the LDS. Then an OPC-UA Client can find what Servers are availabe by calling "FindServers". Note that the OPC-UA Servers and the LDS should be on the same machine, since it is a "Local" Discovery.

**Comment by rikku1004** [comment]
@erhardgrishaber thank you for your help.. I am beginning to understand it more clearly now..

**Comment by rikku1004** [comment]
@erhardgrishaber hello again.. I've tried running the LDS on cmd I am getting this error.. Can I ask for your help on how to solve this?
![error](https://user-images.githubusercontent.com/34506561/44705803-46a6f100-aad2-11e8-8492-609ddd6f53d9.png)

**Comment by erhardgrishaber** [comment]
The user (Windows) that you are logged in has not enough privileges. Try to run it as Admin.
What happens is that LDS is trying to start the "OPCF Bonjour" Service (it is a runtime dependency) but failed to get a handle to the Service due to low access rights ("Access is denied").

**Comment by rikku1004** [comment]
I see.. Also @erhardgrishaber does this LDS works with the demo server from matrikon? found this link https://www.matrikonopc.com/downloads/1362/index.aspx

**Comment by erhardgrishaber** [comment]
I don't use Matrikon so I don't know. It depends on the implementation of the Server. Some of them do register to the LDS others don't.

**Comment by rikku1004** [comment]
@erhardgrishaber okay.. I'll try it once the account issue is resolved.. Thanks a lot..

**Comment by dk2129** [comment]
This issue is closed as there was no further feedback since February.

The recent discussion was not related to the original issue. 
Please create a new issue if necessary.
