### ISSUE TITLE
Commits does not have a tag for release

### ISSUE THREAD

**Issue by JochenKalmbach** [OPCFoundation/UA-LDS#39]
It would be great, if the commits would have tags for each release... so we could know which commits are in a release or not... the only tag was 1.03.355... the latest release is 1.03.371 but there are no tags... also there is a crash report from version 1.03.367 which is also unclear which commit is used.

**Comment by erhardgrishaber** [comment]
Fixed in the last two releases: 1.03.371 and 1.03.400
