### ISSUE TITLE
Inconsistency between ualds.ini and source code 

### ISSUE THREAD

**Issue by ThomasRothfuss** [OPCFoundation/UA-LDS#40]
ualds.ini (also ualds.conf) allows the security policy none:
Endpoints/0/SecurityPolicies = SecurityPolicy_None, SecurityPolicy_Basic128Rsa15, SecurityPolicy_Basic256

Within registerserver.c (registerserver2.c) OPCUA_SECURECHANNEL_MESSAGESECURITYMODE_NONE is not allowed: in that case the function ualds_registerserver (ualds_registerserver2) returns OpcUa_BadServiceUnsupported

**Comment by erhardgrishaber** [comment]
The RegisterServer/RegisterServer2 services are secured only. From OPC-UA Spec: "A Server shall establish a SecureChannel with the Discovery Server before calling this Service." That is why it is rejected if a Server tries to register itself with None.
You can use the NoneSecuredPolicy for the FindServers/FindServertsOnNetwork services (Client-only).

**Comment by ThomasRothfuss** [comment]
Ok I see. We used the old LDS so far (before 26.01.2017). So the behavior of the LDS has changed for us.
Now I updated to a new version of our OPC UA SDK. It runs with the latest LDS version.
