### ISSUE TITLE
LDS enters endless loop in checkConfigConsistency() 

### ISSUE THREAD

**Issue by GMarquardt** [OPCFoundation/UA-LDS#42]
I started LDS 1.03.371 with an ini file which contains more than 2 Servers in section [RegisteredServers]. This causes an endless loop in checkConfigConsistency().
There are two nested for loops (for (i = 0; i < tmpVal; i++) ...) and for (i = 0; i < tmpVal2; i++) which use the same index variable (i). The inner Loop Ends with i == tmpVal2 which normaly evals to 2. If tmpVal (the count of the servers) is greater than 2 the outer loop never ends.

**Comment by JochenKalmbach** [comment]
I think you mean "settings.c(1203)", or? "i" should be replaced with "j".... see also line 1261...

**Comment by GMarquardt** [comment]
Yes, I think replacing "i" by "j" at "settings.c(1203) is a good solution for the issue.

**Comment by erhardgrishaber** [comment]
The observation is correct; code commited on master.

**Comment by erhardgrishaber** [comment]
Yes I did miss it. Thank you.

**Comment by erhardgrishaber** [comment]
Fixed in LDS 1.03.400
