### ISSUE TITLE
Massive memory leak and high CPU usage

### ISSUE THREAD

**Issue by JochenKalmbach** [OPCFoundation/UA-LDS#43]
The LDS stores the registered servers in an internal structure like an ini file (see settings.c) as a linked list. Now, every time "ualds_expirationcheck (ualds.c)" is triggered, it will discard all entries in the list and will add the new list after the server gets checks and optionally entries where removed.
The problem is now, that the removal of the entry from the internal ini section does not really remove the entry, instead it just markes this entry as "Invalid".
This means, that every time this server-list gets "re-created" we get a memory leak in the size of the server list. This "ualds_expirationcheck" is normally only called about every 5 seconds... also if you use the LDS and a server is not yet registers which a client wants to access, there might be the situation, that this function is trigger more often.
Together with a long running machine (several days), this leads to a memory leak (from 2 MB to 350 MB) and to a high CPU load, because it must traverse several millions of "invalid" entries (about 80-100% for one CPU kernel).

This is a major issue...

Be are currently implementing a fix for this problem and we will create a pull request.

**Comment by erhardgrishaber** [comment]
Fixed in LDS 1.03.400
