### ISSUE TITLE
How to use OPC-UA Server and Client on Windows XP Embedded

### ISSUE THREAD

**Issue by ptanguay** [OPCFoundation/UA-LDS#45]
Hello, In my project, I need to implement an OPC Server and Client on Windows XP Embedded SP2. I created my own applications based on your examples and my applications work well on my personal computer with Windows 7. But on Windows XPE, I have problem with security and certificates. Here is the resume:

I tried to install "opc-ua-local-discovery-server-1.03.400.431". I got a successful message but when I check the services, I cannot see the services "Apple Bonjour" and "UA Local Discovery Server". So I expect the installation was not made correctly. Also, when I double-click on the file "Opc.Ua.DiscoveryServer.exe", I got the message "The procedure entry point GetLogicalProcessorInformation could not be located in the dynamic link library KERNEL32.dll. 
So my questions are:

    - Is is possible to install UA Local Discovery Server on Windows XPE SP2 ?
    - If yes, could someone send me an old version of this server ? Like 1.00, 1.01, 1.02 ?
    - Is it possible to use OPC-UA Server and Client without having this server installed ?

After that, I copied the file "Opc.Ua.CertificateGenerator.exe" next to my executable files to be able to generate each time a new self-signed certificate for both applications. Now, I'm able to start my server but when I try to connect my client to it, I got the message "Certificate validation failed. NotSignatureValid: The signature of the certificate can not be verified.". So my questions are:

    - Why I got this message ?
    - Could someone help me to understand how the certificate and signature validation work ?
    - Does CertificateGenerator use encryption that it is not recognized on Windows XPE SP2 ?

I also tried to use OPC UA Configuration Tool but once again, I still receive the error message "NotSignatureValid". Could I generate my own certificates to resolve my problem "NotSignatureValid".

Thank you for your help. I spent one week to understand what happen but without results.

**Comment by opcfoundation-org** [comment]
1) XP requires SHA1 signatures on certificates which are no longer allowed on modern OSes;
2) The setting the CertificateGenerator -hashSize parameter to 160 should give you SHA1 signed certs;
3) You can rebuild the code using a compiler compatible with XP from the source on GitHub.
