### ISSUE TITLE
Error building on centos 7.5

### ISSUE THREAD

**Issue by eoursel** [OPCFoundation/UA-LDS#47]
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- checking for module 'avahi-compat-libdns_sd'
--   found avahi-compat-libdns_sd, version 0.6.31
-- Configuring done
-- Generating done

/mnt/Home/vagrant/code/opc_f/UA-LDS/ualds.c: In function ‘ualds_load_certificate’:
/mnt/Home/vagrant/code/opc_f/UA-LDS/ualds.c:688:9: attention : passing argument 4 of ‘g_PkiProvider.LoadPrivateKeyFromFile’ makes pointer from integer without a cast [enabled by default]
         &g_server_key);
         ^
/mnt/Home/vagrant/code/opc_f/UA-LDS/ualds.c:688:9: note: expected ‘struct OpcUa_ByteString *’ but argument is of type ‘int’
/mnt/Home/vagrant/code/opc_f/UA-LDS/ualds.c:688:9: erreur: too many arguments to function ‘g_PkiProvider.LoadPrivateKeyFromFile’
/mnt/Home/vagrant/code/opc_f/UA-LDS/ualds.c:698:13: attention : passing argument 4 of ‘g_PkiProvider.LoadPrivateKeyFromFile’ makes pointer from integer without a cast [enabled by default]
             &g_server_key);
             ^
/mnt/Home/vagrant/code/opc_f/UA-LDS/ualds.c:698:13: note: expected ‘struct OpcUa_ByteString *’ but argument is of type ‘int’
/mnt/Home/vagrant/code/opc_f/UA-LDS/ualds.c:698:13: erreur: too many arguments to function ‘g_PkiProvider.LoadPrivateKeyFromFile’
gmake[2]: *** [CMakeFiles/ualds.dir/ualds.c.o] Erreur 1
gmake[1]: *** [CMakeFiles/ualds.dir/all] Erreur 2
gmake: *** [all] Erreur 2

Any idea?

**Comment by erhardgrishaber** [comment]
Tested today with latest sources (LDS v1.03.400) on CentOS 7.2 and it works.
The error (you received) is related to the communication with the UaStack. In the last release (of the LDS), the dependencies to the UaStack have been updated; so if you have older code downloaded for the stack, please delete it and donwload it again.
