### ISSUE TITLE
Certificate Generator Error

### ISSUE THREAD

**Issue by entitification** [OPCFoundation/UA-LDS#48]
Upon installing the 1.03.400 release I came to notice that UA LDS no longer registers my servers and UA Sample Client is blind in finding them. This was weird as everything seemed OK! a line by line comparison of *.der files generated with new certificate generator with previous ones show that the property BasicConstraints=>SubjectType is set to "EndEntity" in new certificates whereas previous ones' SubjectType was "CA"! So when subject type is EndEntity , LDS doesn't register the servers on itself. This is my understanding of the issue so if I'm wrong please enlighten me.

**Comment by erhardgrishaber** [comment]
Tested LDS (v1.03.400) with two DemoServers that have the BasicConstraints=>SubjectType set to EndEntity and the registration was successfull.

If there were new certificates generated, please make sure that both Servers (LDS and youre Server) trust each other, meaning LDS certificate is in the trusted folder of youre Server, and youre Server certificate is in the trusted folder of the LDS. It is important that both certificates are exchanged.

Is there any error entry in the LDS log file (opcualds.log) ?

If it is just a certificate validation problem on the LDS, it can be checked by a workaround. Stop the LDS service, change in the configuration file (ualds.ini): uncomment the line "AllowLocalRegistration = yes". This will bypass the certificate trust validation. Start the LDS service.

If the problem persists: is there a way to reproduce the problem ? Can you provide something that can help me investigate ?

**Comment by entitification** [comment]
Tested on a new system and these are the results (My software creates certificates automatically using CertificateGenerator.exe)
* Servers with "BasicConstraints=>SubjectType set to EndEntity" are not visible to UASampleClient and my own clients.
* Turning AllowLocalRegistration ON, results in servers being successfully registered on LDS and visible to clients.
* Also, turning it off and generating the certificates using UAConfigurationTool to generate certificates with "BasicConstraints=>SubjectType set to CA" also works: Servers are registered on LDS and visible to SampleClient.
* After this, deleting the certificates and allowing them to be automatically generated (which employs the CertificateGenerator installed by LDS) generates EndEntity and the servers are again invisible to LDS!
NOTE: For each step, and after each change, I restart UALDS service to see the results.
NOTE2: The "SubjectType=CA" is the only difference I could find between current and previous LDS. But I'm not sure if this is the problem causing this scenario!
PS: I've attached the log file since the time LDS was installed:
[opcualds.log](https://github.com/OPCFoundation/UA-LDS/files/2767579/opcualds.log)

**Comment by erhardgrishaber** [comment]
@entitification: From the log file you provided, it is clear that the certificate validation failed on the LDS.
I made the following test:
1. Created a test application that registeres to the LDS (v1.03.400)
2. Generated certificates with Opc.Ua.CertificateGenerator.exe (v.1.1.339) (found in folder c:\Program Files (x86)\Common Files\OPC Foundation\UA\v1.0\Bin\) with the following command:
Opc.Ua.CertificateGenerator.exe -cmd issue -sp . -an MyApp -au urn:MyH
pany -dn MyHost -pw MyCertFilePassword -pem true
The BasicConstraints=>SubjectType set to EndEntity.
3. Exchanged certificates between testApplication and LDS
4. Started TestApplication
5. Registration succeded. I can see it with UaExpert.

Questions:
1. Are the application (LDS + Opc.Ua.CertificateGenerator) versions correct ?
2. Can you provide the command line parameters used by the Opc.Ua.CertificateGenerator.exe ?
3. Is it possible to attache the actual certificate (der + pem files) thet is rejected by the LDS ?

**Comment by erhardgrishaber** [comment]
@entitification: A new release is planned for the LDS. It would be great if this issue could be reproduced and fixed. Could you give any further information that could help ? See questions in previous comment.

**Comment by erhardgrishaber** [comment]
Issue closed due to inactivity by the original reporter. Please try the latest LDS release v1.03.401
