### ISSUE TITLE
If the option EnableZeroconf = no, the ualds_findserversonnetwork will never return registered servers

### ISSUE THREAD

**Issue by cgapeart** [OPCFoundation/UA-LDS#49]
Found this on the current master (.400) version under linux.  I was trying to figure out why my server was not showing up despite a succesfull registration (according to the protocol via wireshark).  Code inspection found that the UDNS and normal UA based FindServersOnNetwork service call share a list of servers.  However, that list is only initialized from the settings system if ualds_findserversonnetwork_start_internal is called.  If I turn off zeroconf in the .conf file, and start the UALDS under GDB with a breakpoint set ualds_findserversonnetwork_start_internal() is never called.

I suspect this is not the desired operation - there isn't much point in being able to disable zeroconf if it means the standard opc.tcp discovery mechanism is broken.

**Comment by cgapeart** [comment]
Similarly, it is unclear how the list of servers used in findserversonnetwork.c would ever be updated if zeroconf is disabled. ualds_registerserver will only flush the listings and presumably update that list if zeroconf is enabled (registerserver.c:200)

**Comment by cgapeart** [comment]
Upon further review, I wonder if FindServersOnNetwork shouldn't work when zeroconf was disabled.  If that was the intent, perhaps the LDS should return a Bad_ServiceUnsupported or other appropriate response code for the FindServersOnNetwork service call.  At least on UA Client (UA Expert) appears to try FindServersOnNetwork first, and won't fallback on FindServers if the service call is successful (even when it is supposed to be treating it as an LDS).

**Comment by cgapeart** [comment]
I tested the system I was looking at after adding 
`if(!g_bEnableZeroconf)
{
  OpcUaReturnErrorIfBad(OpcUa_BadServiceUnsupported);
}`

to ualds_findserversonnetwork(...) just after the initializers at the top of the function in findserversonnetwork.c

I can confirm that UA Expert now falls back on the FindServers call, and the server I was registering is correctly found and I can then connect to it.

Something is not quite right in how the UA-LDS handles the FindServersOnNetwork call in this case.
Note that the server in question does not do any mDNS discovery announcements on it's own.  It is going to rely on the LDS for the moment.

**Comment by FischerSeb** [comment]
No error. See last comment.

**Comment by erhardgrishaber** [comment]
Fixed in LDS v1.03.401
