### ISSUE TITLE
Servers cannot connect to LDS if computer was renamed.

### ISSUE THREAD

**Issue by K47S** [OPCFoundation/UA-LDS#5]
A .Net OPC UA Server calls the method StandardServer.RegistrationValidator_CertificateValidation() when registering with the LDS. If the computers hostname changed (for example by renaming it) without deleting the LDSs own certificates the OPC UA Server cannot register with the LDS as the domain in the LDS certificate doesn't match the machines hostname. 

I don't know if this is expected behaviour. I think the LDS should check its own certificate on startup and replace it if necessary.

**Comment by SparhawkSoftware** [comment]
Certificates cannot be automatically replaced by applications without breaking security. If the admin changes the domain name then the LDS certificate must be deleted by the admin which will trigger the creation of a new certificate.
