### ISSUE TITLE
Docker Linux LDS fails to run

### ISSUE THREAD

**Issue by realholgi** [OPCFoundation/UA-LDS#51]
After fixing the obvious #50, it still does not run, because LDS fails to parse the config file:

`$ docker build -t lds .`
`$ docker run -it -h lds --net=host lds:latest`

`$ cat /var/log/opcualds.log`
`Configuration error: Could not read number of endpoints from config file. `

config file is the unmodified etc/ualds.conf from this repo:

> \# Endpoint configuration
> \# Number of available endpoints
> Endpoints/size = 1
> Endpoints/0/Url = opc.tcp://[gethostname]:4840
> Endpoints/0/SecurityPolicies = SecurityPolicy_None, SecurityPolicy_Basic128Rsa15, SecurityPolicy_Basic256

Any ideas?

**Comment by erhardgrishaber** [comment]
@realholgi : With the steps you provided, I could reproduce the issue.
I think the log entry is misleading (I will improve that). In my case the actual problem was that the hostname that was provided as parameter in the command line (-h lds) could not be resolved to an IP address. After manually updating the /etc/hosts file, I managed to start the LDS.
To check if you have the same problem, try to start the LDS with the following command "./opcualds -d -c /lds/etc/ualds.conf" in the /lds/build/bin folder in the docker container. It will print to the console all log entries. You should see the message "Opening endpoint failed with error ..."
Please let me know if this helped.

**Comment by realholgi** [comment]
@erhardgrishaber : I now tried to use docker-compose to run lds, so there is a hostname and a network configured properly. Now I can ping myself by name (lds) and see the configured name in the logs, but it still does not work.

docker-compose.yml (used with your supplied Dockerfile):
```
version: "3.4"

services:
  lds:
    container_name: lds
    image: lds:latest
    build:
      context: UA-LDS
      dockerfile: Dockerfile
    hostname: lds
    expose:
      - "5353"
      - "4840"
```
and now `docker-compose run lds`

```
[ ok ] Starting enhanced syslogd: rsyslogd.
[ ok ] Starting system message bus: dbus.
root@lds:/#
```
Hmmmm....

```
cd /lds/build/bin/
./opcualds -d -c /lds/etc/ualds.conf
```

results in 

```
Wed Feb 13 14:09:13 [85]: Opening endpoint 'opc.tcp://lds:4840'...
Wed Feb 13 14:09:13 [85]: Opening endpoint failed with error 0x80050000.
Wed Feb 13 14:09:13 [85]: [uastack] OpcUa_SocketManager_Delete: Invalid Socket Manager!
Wed Feb 13 14:09:13 [85]: Delete Zeroconf registration timer
Wed Feb 13 14:09:13 [85]: Delete Zeroconf browse timer
..
Wed Feb 13 14:13:40 [132]: Terminating with exitcode=1
```

What am I doing wrong?

**Comment by erhardgrishaber** [comment]
@realholgi : 
Using the provided docker-compose file, the container started but exited immediately with 0; so I added "tty: true" + a volume mapping, so I can have easy access to the certificates:
    volumes:
      - /tmp/opcualds/pki/:/opt/opcfoundation/ualds/pki/
Now the container is not exiting.
From a second console, I connected to the running container and could see the LDS running:
 
![lds-docker](https://user-images.githubusercontent.com/17177166/52772520-5b0b8580-3041-11e9-8fb6-57b996af713f.jpg)

Can you check from console that the LDS is running ? ps aux

**Comment by realholgi** [comment]
@erhardgrishaber : The "tty"-line solved my problem, on which I should have thougt myself (or remove the "& bash" in the dockerfile!).

Thanks for helping me out; thank you very much!
