### ISSUE TITLE
Certificate isn't recognized by OPC UA Server?

### ISSUE THREAD

**Issue by jgrossrieder** [OPCFoundation/UA-LDS#52]
Hi,

I've my server generating its own SSL Certificate. This certificate is a self-signed, store in windows store in "UA Applications" and also "Trusted Root Certification Authorities". If I go in the windows certificate, it's now fully recognized as a valid certificate(not even a warning about self-signed certificate).

When I connect to the server using a desktop client, I get a BadCertificateUntrusted, but I'm not sure what is the cause of this issue(since on windows it is correctly recognized).
![certificateerror](https://user-images.githubusercontent.com/7582002/52565168-5909b280-2e06-11e9-97bf-ceb956b08618.jpg)

I tried to use AllowLocalRegistration = yes, and it works, but I would like to have this certificate recognized by OPC UA LDS? 

It makes 3 days that I'm trying this, I tried to increase the logs, but I don't have much more informations:

> Mon Feb 11 13:58:46 [2532]: [uastack] 
> verify error:
> 	num=18:self signed certificate
> 	depth=0
> 	/C=CH/O=XXXX/OU=YYYY/CN=SmallDb
> Mon Feb 11 13:58:46 [2532]: [uastack] 	issuer=/C=CH/O=XXXX/OU=YYYY/CN=SmallDb
> Mon Feb 11 13:58:46 [2532]: [uastack] 
> verify error:
> 	num=18:self signed certificate
> 	depth=0
> 	/C=CH/O=XXXX/OU=YYYY/CN=SmallDb
> Mon Feb 11 13:58:46 [2532]: [uastack] 	issuer=/C=CH/O=XXXX/OU=YYYY/CN=SmallDb
> Mon Feb 11 13:58:46 [2532]: Could not verify certificate in old defualt certificate store (0x801a0000).
> Mon Feb 11 13:58:46 [2532]: [uastack] 
> verify error:
> 	num=18:self signed certificate
> 	depth=0
> 	/C=CH/O=XXXX/OU=YYYY/CN=SmallDb
> Mon Feb 11 13:58:46 [2532]: [uastack] 	issuer=/C=CH/O=XXXX/OU=YYYY/CN=SmallDb
> Mon Feb 11 13:58:46 [2532]: Could not verify certificate in old edited certificate store (0x801a0000).
> Mon Feb 11 13:58:46 [2532]: Verifying certificate in windows store returned 0x00000000.
> Mon Feb 11 13:58:46 [2532]: Verifying certificate in windows store succeeded.
> Mon Feb 11 13:58:46 [2532]: ualds_endpoint_callback called: Event=SecureChannelOpened, SecureChanneldId=0x00000026, uStatus=0x00000000
> Mon Feb 11 13:58:46 [2532]: ualds_endpoint_callback: SecureChannel 0x00000026 opened with http://opcfoundation.org/UA/SecurityPolicy#Basic256 in mode 2 status 0x00000000!
> Mon Feb 11 13:58:46 [2532]: Registering server urn:MyComputer:YYYY:OpcUaServer:SmallDb.
> Mon Feb 11 13:58:46 [2532]: ualds_endpoint_callback called: Event=SecureChannelClosed, SecureChanneldId=0x00000026, uStatus=0x00000000
> Mon Feb 11 13:58:46 [2532]: ualds_endpoint_callback: SecureChannel 0x00000026 closed with status 0x00000000!

**Comment by cacamille3** [comment]
Please check Unified Automation UA Experts [documentation](https://documentation.unified-automation.com/uaexpert/1.5.0/html/first_steps.html)

**Comment by jgrossrieder** [comment]
@cacamille3 I would love too, but this is just a test client, my biggest issue is for registering OPC UA LDS, I know how to trust the certificate on the client, it was just to provide more informations

**Comment by cacamille3** [comment]
_"When I connect to the server using a desktop client, I get a BadCertificateUntrusted, but I'm not sure what is the cause of this issue(since on windows it is correctly recognized)."_ -> You should click the **Trust Server Certificate** button then this dialog will not popup anymore when connecting to your Server.

To make it easy: Each OPC UA Client has its own Certificate Manager that allows you to allow/block OPC UA Server based on their certificate

**Comment by jgrossrieder** [comment]
Yeah I know this... like I said, this is about OPC UA **LDS**, not my client. The client is only used for test purpose.

**Comment by cacamille3** [comment]
> Yeah I know this... like I said, this is about OPC UA **LDS**, not my client. The client is only used for test purpose.

What is your issue then ? It is not clear to me...

**Comment by jgrossrieder** [comment]
> > Yeah I know this... like I said, this is about OPC UA **LDS**, not my client. The client is only used for test purpose.
> 
> What is your issue then ? It is not clear to me...

How to make OPC UA LDS showing my server. Currently it doesn't and has errors in the logs that it cannot find valid certificate in my windows certificate store.

**Comment by cacamille3** [comment]
I think someone is having the same issue than you : #48

**Comment by erhardgrishaber** [comment]
@jgrossrieder : A new release is planned for the LDS. It would be great if this issue could be reproduced and fixed. Could you give any further information that could help ?
1. How are you're certificates created ? steps ?
2. Is it possible to attache the actual certificate (der + pem files) that is rejected by the LDS ?

**Comment by jgrossrieder** [comment]
@erhardgrishaber The issue was that the service URI was missing in the SSL and I was having no error with that :(.

**Comment by erhardgrishaber** [comment]
@jgrossrieder : Can this issue be closed ?

**Comment by jgrossrieder** [comment]
@erhardgrishaber Yeah, I've found a workaround, not that nice, and it require me to be admin, but it works.
