### ISSUE TITLE
Possible malloc(0)

### ISSUE THREAD

**Issue by cacamille3** [OPCFoundation/UA-LDS#54]
Hi,

I think the LDS can call malloc with 0 as size in case of a FindServers Request when the Client send a (or multiple) ServerUris and there is no match with the one available on the LDS.

IMO `malloc(0)` shall be avoid since the behavior might depends on the library implementation 

> If size is zero, the return value depends on the particular library implementation (it may or may not be a null pointer), but the returned pointer shall not be dereferenced.

https://github.com/OPCFoundation/UA-LDS/blob/a58a60e9512c51004416d096c3dfddd7de77e259/findservers.c#L149

**Comment by bernd-edlinger** [comment]
The platform layer is supposed to handle this correctly.

**Comment by cacamille3** [comment]
`malloc(0)` returning `NULL` will lead to `uStatus = OpcUa_BadOutOfMemory;`
In some implementation the FindServers will return an error and in some other it will return OpcUa_Good with empty list of Servers...

**Comment by erhardgrishaber** [comment]
Fixed in LDS v1.03.401
