### ISSUE TITLE
Improve logging for Certificate Validation

### ISSUE THREAD

**Issue by AlinMoldovean** [OPCFoundation/UA-LDS#55]
All validation errors should be logged with specific details according to spec requirements defined in Part. 4

Get rid of messages that are not useful for the administrator.
Default log level should not include debug information.

**Comment by erhardgrishaber** [comment]
Fixed in LDS v1.03.401
Messages that are not useful for Admin were moved to Debug level.
If validation failed, message is logged on Error level with thumbprint and status code (pretty print version).
