### ISSUE TITLE
No merge module or setup for 1.03.401

### ISSUE THREAD

**Issue by MD-V** [OPCFoundation/UA-LDS#57]
Hello,

could you please provide a new setup and merge module for version 1.03.401?
Thank you very much.

**Comment by erhardgrishaber** [comment]
@MD-V : The remaining Issues will be fixed this week.  After that it will go through testing and a new setup will be published. It will probably be ready in the beginning of June.

**Comment by MD-V** [comment]
@erhardgrishaber Thank you very much for the information.
