### ISSUE TITLE
DiscoveryClients can block the LDS

### ISSUE THREAD

**Issue by K47S** [OPCFoundation/UA-LDS#6]
Hello,

I may have found a way that malicious OPC-UA clients can block the LDS for other clients:

//Create atleast 50 DiscoveryClients via the SDK (.NET example)
for (var i = 0; i < 50; i++)
            {
                var discoveryClient = DiscoveryClient.Create(Uri discoveryUrl);
                discoveryClient.OperationTimeout = 60000;
                //Query the LDS
                var endpoints = discoveryClient.GetEndpoints(null);
                //Don't close the clients
            }

After this the LDS will not reply to any request from other clients until the malicious client is closed .
I assume this is because the LDS has a session limit of 50. Wouldn't it be good to forcefully close old sessions it the limit of 50 sessions is reached?

**Comment by dk2129** [comment]
The OPC Foundation just released a BETA version of the LDS V1.03:  
https://opcfoundation.org/developer-tools/developer-kits-unified-architecture/local-discovery-server-lds/ 
If you can, please retry your test scenario with this version.

**Comment by K47S** [comment]
I have now tested the same code on the new LDS 1.03.348. 
It blocks also but with >=100 DiscoveryClients

**Comment by sorintopan** [comment]
LDS recovers according to the ExpirationMaxAge parameter configured in ualds.ini
# maximum age of registered server entries before they expire in seconds. (Default=600)
ExpirationMaxAge = 600

If 100 secure channels created, LDS is not creating new ones (known limitation). If on those channels are not sent requests for 10 minutes(see the parameter above), LDS removes them and allows the creation of new ones.
