### ISSUE TITLE
Registering Server in LDS

### ISSUE THREAD

**Issue by jdhanasekar** [OPCFoundation/UA-LDS#60]
Hi All,

I am new to OPC UA. I am working on to set up a LDS server. I have downloaded the source from ```https://github.com/OPCFoundation/UA-LDS/```. I have built the source in my Linux system and run the binary by this command ``` ./opcualds -d -c -p Starts ```.

I am running Kepware and UA Automation Server in my Windows host. 
I don't know how to register these server with LDS server running Linux host.

LDS and OPC server should run in same host ?. Then only, I can able to register the server

Can you please help me on this?

I have attached the log, Please view it.

```
Wed Feb  5 19:03:40 [24000]: Create Zeroconf registration timer with interval 5
Wed Feb  5 19:03:40 [24000]: ualds_findserversonnetwork_start_internal: Call DNSServiceBrowse for service type _opcua-tcp._tcp
Wed Feb  5 19:03:40 [24000]: ualds_findserversonnetwork_start_internal: Call DNSServiceBrowse for service type _opcua-tls._tcp
Wed Feb  5 19:03:40 [24000]: ualds_findserversonnetwork_start_internal: Call DNSServiceBrowse for service type _opcua-http._tcp
Wed Feb  5 19:03:40 [24000]: Create Zeroconf browse timer with interval 5
Wed Feb  5 19:03:40 [24000]: Opening endpoint 'opc.tcp://quanta:4840'...
Wed Feb  5 19:03:40 [24000]: Endpoint is open.
Wed Feb  5 19:03:42 [24000]: ualds_DNSServiceBrowseReply: received service:
Wed Feb  5 19:03:42 [24000]:                              interfaceIndex 2
Wed Feb  5 19:03:42 [24000]:                              serviceName    UA Local Discovery Server on BLRB1DT166.VTPPL.COM
Wed Feb  5 19:03:42 [24000]:                              regtype        _opcua-tcp._tcp.
Wed Feb  5 19:03:42 [24000]:                              replyDomain    local.
Wed Feb  5 19:03:42 [24000]: ualds_DNSServiceBrowseReply: Call DNSServiceResolve
Wed Feb  5 19:03:44 [24000]: ualds_DNSServiceResolveReply: resolved service:
Wed Feb  5 19:03:44 [24000]:                               interfaceIndex 2
Wed Feb  5 19:03:44 [24000]:                               fullname       UA\032Local\032Discovery\032Server\032on\032BLRB1DT166\.VTPPL\.COM._opcua-tcp._tcp.local.
Wed Feb  5 19:03:44 [24000]:                               hosttarget     BLRB1DT166.VTPPL.COM.
Wed Feb  5 19:03:44 [24000]:                               port           4840
Wed Feb  5 19:03:46 [24000]: ualds_DNSServiceRegisterReply: server registered:
Wed Feb  5 19:03:46 [24000]:                                flags 0
Wed Feb  5 19:03:46 [24000]:                                error 0
Wed Feb  5 19:03:46 [24000]:                                name UA Local Discovery Server on quanta
Wed Feb  5 19:03:46 [24000]:                                regtype _opcua-tcp._tcp.
Wed Feb  5 19:03:46 [24000]:                                domain local.
Wed Feb  5 19:03:46 [24000]: Announcing server urn:[gethostname]:UALocalDiscoveryServer via Zeroconf succeeded
Wed Feb  5 19:03:47 [24000]: ualds_DNSServiceBrowseReply: received service:
Wed Feb  5 19:03:47 [24000]:                              interfaceIndex 2
Wed Feb  5 19:03:47 [24000]:                              serviceName    UA Local Discovery Server on quanta
Wed Feb  5 19:03:47 [24000]:                              regtype        _opcua-tcp._tcp.
Wed Feb  5 19:03:47 [24000]:                              replyDomain    local.
Wed Feb  5 19:03:47 [24000]: ualds_DNSServiceBrowseReply: Call DNSServiceResolve
Wed Feb  5 19:03:48 [24000]: ualds_DNSServiceBrowseReply: ignoring known service UA Local Discovery Server on quanta / _opcua-tcp._tcp.
Wed Feb  5 19:03:49 [24000]: ualds_DNSServiceBrowseReply: ignoring known service UA Local Discovery Server on quanta / _opcua-tcp._tcp.
Wed Feb  5 19:03:49 [24000]: ualds_DNSServiceResolveReply: resolved service:
Wed Feb  5 19:03:49 [24000]:                               interfaceIndex 2
Wed Feb  5 19:03:49 [24000]:                               fullname       UA\032Local\032Discovery\032Server\032on\032quanta._opcua-tcp._tcp.local.
Wed Feb  5 19:03:49 [24000]:                               hosttarget     quanta.local.
Wed Feb  5 19:03:49 [24000]:                               port           4840
Wed Feb  5 19:03:50 [24000]: ualds_DNSServiceBrowseReply: ignoring known service UA Local Discovery Server on quanta / _opcua-tcp._tcp.
Wed Feb  5 19:03:51 [24000]: ualds_DNSServiceBrowseReply: ignoring known service UA Local Discovery Server on quanta / _opcua-tcp._tcp.



```

**Comment by erhardgrishaber** [comment]
@jdhanasekar The purpose of the LDS is for Servers to register locally, as the name suggests LocalDiscoveryServer. So the LDS needs to run on the same host as the Servers. Note that there is an official LDS setup for Windows; you can download it from the OPCFoundation website.  
Note: since the registration to the LDS is secured only, make sure that the certificates are trusted.

**Comment by jdhanasekar** [comment]
Thanks for response. 

I am not getting nmake error in Windows. 
Windows requires visual studio cmd prompt to run build_ualds.bat. 
Is there other way to install this ?

**Comment by erhardgrishaber** [comment]
Download the setup from here: https://opcfoundation.org/developer-tools/samples-and-tools-unified-architecture/local-discovery-server-lds/

**Comment by jdhanasekar** [comment]
Yes.. I have already installed this tool. But I don't know how to extract information from this.
Will I get any GUI from this tool ?

**Comment by erhardgrishaber** [comment]
There is no dedicated GUI tool for the LDS, but you can use some of the existing generic Clients that can  interrogate the LDS for information, like: "UaExpert" or "dataFEED OPC UA Client".

**Comment by jdhanasekar** [comment]
I have installed LDS in my Window Host. When I try to access the ```LDS (opc.tcp://localhost:4840)``` in "UaExpert", I am getting below error. 

```Error 'BadServiceUnsupported' was returned during CreateSession.```

![image](https://user-images.githubusercontent.com/51257095/74000946-dc190680-498f-11ea-995f-33b125293e55.png)

**Comment by erhardgrishaber** [comment]
The LDS does not support (intentionally) the CreateSession and it does not have an AddressSpace. The supported service calls are described in the OPC UA Specification Part 12. The important service calls are: for Server: RegisterServer and RegisterServer2; for a Client: FindServers and FindServersOnNetwork.
See the bollow screenshot for example. The Client is calling FindServersOnNetwork and if fails, it falls back to the FindServers.
![LDS_UAExpert](https://user-images.githubusercontent.com/17177166/74131971-39aa8e80-4bee-11ea-8104-594083cef455.jpg)

**Comment by jdhanasekar** [comment]
I am running two server, Kepware and Ua Ansi C server. Nothing is coming under Discovery in UaExpert Tool.
I have attached the screen shot.

![image](https://user-images.githubusercontent.com/51257095/74144067-126db480-4c22-11ea-8b9b-1d264cabf432.png)

**Comment by erhardgrishaber** [comment]
1. From the last entry in the Client log (screenshot that you provided) it shows that it did get the endpoint of the LDS itself, but it intentionally discarded it from showing in the results. This means that the LDS is running and the Client did manage to communicate with the LDS.
2. The Server needs to register to the LDS, but not all Servers are implemented to do so. I don't know it the Servers that you use are actually registering or not.
3. If they do, the certificates need to be trusted. Please check in the "rejected" folder of the LDS. There are two places: 
a) C:\ProgramData\OPC Foundation\UA\pki\rejected\certs
b) C:\ProgramData\OPC Foundation\UA\Discovery\pki\rejected
If there are certificates in that folder, move them to the corresponding "trusted" folder.
4. Assuming that all the above don't help, you can try to check the log file of the LDS for extra information: C:\ProgramData\OPC Foundation\UA\Discovery\opcualds.log
There is also a configuration file where you can change the existing settings: C:\ProgramData\OPC Foundation\UA\Discovery\ualds.ini. A restart of the LDS Service is necessary for any changes to apply.

**Comment by jdhanasekar** [comment]
Thanks for the info.
Still, I am facing the issue. Debugging is in progress....

**Comment by erhardgrishaber** [comment]
@jdhanasekar Can this issue be closed ?

**Comment by jdhanasekar** [comment]
Yes. You can close this issue. 
Thanks for your support.
