### ISSUE TITLE
Documentation link is not valid

### ISSUE THREAD

**Issue by matthewGEA** [OPCFoundation/UA-LDS#61]
When installing version 1.03.401.438-20190618, the Documentation URL that is installed into the start menu points to the following location:
http://opcfoundation-onlineapplications.org/LDS/1.03/UALDS.htm

This link does not work, but the documentation appears to be available at:
http://opcfoundation-onlineapplications.org/LDS/

**Comment by erhardgrishaber** [comment]
The upcoming LDS release (in a few weeks) will fix problem. The new link will be https://apps.opcfoundation.org/LDS/

**Comment by erhardgrishaber** [comment]
The new LDS-ME version will be 1.04.402
