### ISSUE TITLE
OPC.HTTPS DiscoveryUrls come out as OPC.TCP DiscoveryUrls from FindServersOnNetwork

### ISSUE THREAD

**Issue by jouniaro** [OPCFoundation/UA-LDS#63]
For example, Prosys OPC UA Simulation Server when registered comes out from FindServers as:
200421 152526.650     TUaLocalDiscoveryClient.FindServers: 1: TUaApplicationDescription $03A39010 (56 bytes)
200421 152526.651     TUaLocalDiscoveryClient.FindServers:   ApplicationUri='urn:prosys01:OPCUA:SimulationServer'
200421 152526.652     TUaLocalDiscoveryClient.FindServers:   ProductUri='urn:prosysopc.com:OPCUA:SimulationServer'
200421 152526.652     TUaLocalDiscoveryClient.FindServers:   ApplicationName=() SimulationServer@prosys01
200421 152526.653     TUaLocalDiscoveryClient.FindServers:   ApplicationType=0
200421 152526.654     TUaLocalDiscoveryClient.FindServers:   GatewayServerUri=''
200421 152526.655     TUaLocalDiscoveryClient.FindServers:   DiscoveryProfileUri=''
200421 152526.656     TUaLocalDiscoveryClient.FindServers:   DiscoverUrls#0=opc.tcp://prosys01:53530/OPCUA/SimulationServer
200421 152526.657     TUaLocalDiscoveryClient.FindServers:   DiscoverUrls#1=opc.https://prosys01:53443/OPCUA/SimulationServer

and from FindServersOnNetwork as 2 entries:

200421 152527.241     TUaLocalDiscoveryClient.FindServersOnNetwork: 1: TUaServerOnNetwork $03A13560 (40 bytes)
200421 152527.242     TUaLocalDiscoveryClient.FindServersOnNetwork:   RecordId=332
200421 152527.243     TUaLocalDiscoveryClient.FindServersOnNetwork:   ServerName='SimulationServer@prosys01'
200421 152527.244     TUaLocalDiscoveryClient.FindServersOnNetwork:   DiscoveryUrl='opc.tcp://prosys01.local.:53530/OPCUA/SimulationServer'
200421 152527.245     TUaLocalDiscoveryClient.FindServersOnNetwork:   ServerCapabilities#0=DA
200421 152527.246      TUaStackHelper.ToServerOnNetwork: entering...Self=$03A01290(): TUaStackHelper
200421 152527.247      TUaStackHelper.ToServerOnNetwork: leaving...
200421 152527.247     TUaLocalDiscoveryClient.FindServersOnNetwork: 2: TUaServerOnNetwork $03A135C0 (40 bytes)
200421 152527.248     TUaLocalDiscoveryClient.FindServersOnNetwork:   RecordId=333
200421 152527.249     TUaLocalDiscoveryClient.FindServersOnNetwork:   ServerName='SimulationServer@prosys01 (2)'
200421 152527.250     TUaLocalDiscoveryClient.FindServersOnNetwork:   DiscoveryUrl='opc.tcp://prosys01.local.:53443/OPCUA/SimulationServer'
200421 152527.251     TUaLocalDiscoveryClient.FindServersOnNetwork:   ServerCapabilities#0=DA

The hostnames have been changed, but also the protocol scheme has been changed for the second entry.

**Comment by jouniaro** [comment]
Using version 1.03.401

**Comment by erhardgrishaber** [comment]
The defect will be fixed in the next LDS release (in progress). The LDS was not ready to receive the "opc.https" schema as this was introduced in opc-ua spec v1.04 and the LDS was using the v1.03. The hostname change with the ".local." is as expected according to spec.

**Comment by jouniaro** [comment]
Yeah, I got it that 'opc.https' was only introduced in 1.04, so kind of expected. It was just odd that it was changed to 'opt.tcp', which then confuses the clients even more. So, if possible, remove 'invalid' entries or keep them unchanged, would be a more future-proof strategy.

**Comment by erhardgrishaber** [comment]
The new LDS-ME version will be 1.04.402
