### ISSUE TITLE
OPC UA LDS is failed to Find Server

### ISSUE THREAD

**Issue by Arumugam-IA** [OPCFoundation/UA-LDS#64]
I have installed latest OPC UA LDS v1.03.401, both UALDS & OPCF Bonjour Service is running properly in the PC. 

![image](https://user-images.githubusercontent.com/67950462/86752146-c9008480-c05c-11ea-9308-692d3bed2358.png)

But when I try to discover the available server via OPC UA Client(UAExpert) I am getting the following error

Discovery FindServersOnNetwork on opc.tcp://localhost:4840 failed (BadTimeout), falling back to FindServers
Discovery FindServers on opc.tcp://localhost:4840 failed (BadTimeout)
Discovery GetEndpoints on opc.tcp://localhost:4840 failed (BadTimeout)

In addition, i have also seen the OPC UA Discovery logs it has the below information.

Tue Jul 07 14:07:24 [12820]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
Tue Jul 07 14:07:31 [12820]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
Tue Jul 07 14:07:38 [12820]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
Tue Jul 07 14:07:45 [12820]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
Tue Jul 07 14:07:54 [12820]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
Tue Jul 07 14:08:01 [12820]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
Tue Jul 07 14:08:08 [12820]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
Tue Jul 07 14:08:15 [12820]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
Tue Jul 07 14:08:23 [12820]: ualds_zeroconf_registerInternal: DNSServiceRegister returned error -65563
Tue Jul 07 14:08:30 [12820]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
Tue Jul 07 14:08:37 [12820]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563
Tue Jul 07 14:08:44 [12820]: ualds_findserversonnetwork_start_internal: DNSServiceBrowse returned error -65563.

Could you please guide what is wrong here, Did I missed anything? Attached the LDS Log files here.

[opcualds.log](https://github.com/OPCFoundation/UA-LDS/files/4883715/opcualds.log)

I am using Window 10 64-bit OS version 1809.

Thanks.

**Comment by erhardgrishaber** [comment]
Please try the latest LDS release candidate v1.04.402. It has some bug fixes, including a dead-lock. Link: https://opcfoundation.org/developer-tools/samples-and-tools-unified-architecture/local-discovery-server-lds/
The error code -65563 means ServiceNotRunning  (Background daemon not running). It appears that when LDS tries to interrogate the Bonjour Service, it is not running according to the DNS Service Discovery API (Apple's implementation of zero-configuration networking (ZEROCONF))

**Comment by erhardgrishaber** [comment]
Please also check in TaskManager if mDNSResponder.exe is running:
![image](https://user-images.githubusercontent.com/17177166/86788021-61533500-c06e-11ea-9744-56485ab02021.png)

**Comment by erhardgrishaber** [comment]
To check that the Bonjour Service is really running, you can try to use the "Bonjour Browser for Windows".
![image](https://user-images.githubusercontent.com/17177166/86794566-58199680-c075-11ea-8e39-26d44b017c6b.png)

**Comment by Arumugam-IA** [comment]
Hello,
Thanks for the quick information.

Even with latest OPC UA LDS release candidate v1.04.402 the result is same. I am getting the same error from the Discovery log.

I have verified in TaskManager and confirm that "mDNSResponder" is running from this location "_C:\Program Files (x86)\Common Files\OPC Foundation\UA\Discovery\bin_".

I have also validated from Bonjour Browser it doesn;t display any running service rather it shows below error message
![image](https://user-images.githubusercontent.com/67950462/86811483-99bd3800-c09b-11ea-9423-95546e93d6cc.png)

Kindly suggest me if anything else am I missing.

Thanks.

**Comment by erhardgrishaber** [comment]
The error code is the same as the one received by the LDS. For some reason, the Bonjour is refusing the connection from any ClientApp.
You can always try to stop (temporarily) any antivirus programs and firewalls, just to be sure that they are not blocking something, and restart the services.
Another approach could be that you install the Bonjour yourself. If successful, stop the 'OPCF Bonjour' and restart the LDS. At startup the LDS will make sure that the 'Bonjour' service is started (and not the 'OPCF Bonjour'). 
If it still dos't work, you can disable the MulticastExtension feature on the LDS in the configuration file: C:\ProgramData\OPC Foundation\UA\Discovery\ualds.ini  EnableZeroconf = no. Restart the LDS.
