### ISSUE TITLE
No exchange of Endpoints between LDS-ME

### ISSUE THREAD

**Issue by felixkretschmer** [OPCFoundation/UA-LDS#7]
Hi,
I got the installer from opcfoundation.org of the LDS-ME installed at two machines:
- LDS-ME@Server01
  - 1 OPC UA Demo Server registeres here
  - 1 TwinCAT OPC UA Server registers here
- LDS-ME@localhost (my own laptop)

In my understanding, the LDS-ME at server01 broadcasts the registered endpoints to all other LDS-ME in the same subnet (consequently my laptop).
But whenever I browse via custom discovery (with newest UAExpert) at opc.tcp://localhost I don't get any endpoints. If I browse custom discovery at opc.tcp://server01 I get all endpoints of the two registered servers.

Unfortunately the index.htm from the docs is not working in the installer package. So I dont know if I need to configure the two LDS-ME to communicate with each other. Does someone relate to this issue?
Regards, Felix

**Comment by dk2129** [comment]
The Multicast Extension introduces the new Service "FindServersOnNetwork". Clients (like the UAExpert) need to be extended to use this new Service. FindServers continues to return only Servers that are directly registered with the LDS.

**Comment by felixkretschmer** [comment]
Sorry, my bad. Didn't think about it. Got it working via this method from the SDK. Thanks a lot.
