### ISSUE TITLE
Automatically exchange certificates with OPC UA server

### ISSUE THREAD

**Issue by YangboLong** [OPCFoundation/UA-LDS#70]
Before my OPC UA server is able to register itself to the LDS, I had to manually copy the OPC UA server's certificate to the trusted folder of the UA-LDS, and vice versa. Is there a way to automatically exchange certificates to avoid this manual step? I don't find any information about such configuration in the document.

**Comment by JochenKalmbach** [comment]
You might enable this setting: AllowLocalRegistration

https://github.com/OPCFoundation/UA-LDS/blob/4df76c37a6a41443c62bef330a354d9541282088/etc/ualds.ini#L26

**Comment by YangboLong** [comment]
I uncommented the config item and tried again. But the OPC UA server's certificate is still saved to the rejected folder (/opt/opcfoundation/ualds/pki/rejected/certs/). See below trace:
Thu Aug 12 14:34:35 [6151]: ualds_endpoint_callback called: Event=SecureChannelOpened, SecureChanneldId=0x00000001, uStatus=0x00000000
Thu Aug 12 14:34:35 [6151]: ualds_endpoint_callback: SecureChannel 0x00000001 opened with http://opcfoundation.org/UA/SecurityPolicy#None in mode 1 status 0x00000000!
Thu Aug 12 14:34:35 [6151]: ualds_endpoint_callback called: Event=SecureChannelClosed, SecureChanneldId=0x00000001, uStatus=0x00000000
Thu Aug 12 14:34:35 [6151]: ualds_endpoint_callback: SecureChannel 0x00000001 closed with status 0x00000000!
Thu Aug 12 14:34:35 [6151]: ualds_endpoint_callback called: Event=SecureChannelOpened, SecureChanneldId=0x00000000, uStatus=0x801A0000
Thu Aug 12 14:34:35 [6151]: ualds_endpoint_callback: SecureChannel 0x00000000 opened with http://opcfoundation.org/UA/SecurityPolicy#Basic256 in mode 4 status 0x801A0000!
Thu Aug 12 14:34:35 [6151]: [uastack] OpcUa_SecureListener_ProcessRequest: Closing channel due error 0x80130000!
