### ISSUE TITLE
Question about last release

### ISSUE THREAD

**Issue by jopi2016** [OPCFoundation/UA-LDS#71]
Hi,
I'm a bit confused about which is the last release.

On the homepage of the opcfoundation (https://opcfoundation.org/developer-tools/samples-and-tools-unified-architecture/local-discovery-server-lds/) you offer the version 1.04.402.461 as latest release with date of 2022-02-10
![grafik](https://user-images.githubusercontent.com/17023802/158396264-8aa077f5-6e54-457c-9eed-6cfa141b75e9.png)

If I download the offered file (opc-ua-local-discovery-server-1.04.402.461-20220210.zip) and open the Changelog.txt in it I can read that Version 1.04.403 is the newest version contained in this file, although the name of the zip file is 1.04.402.

However on github there does not exist a tag/release for 1.04.402 dated of this year but only last year. Furthermore no tag for 1.04.403 does exist.

So my question is: Which version of the UA-LDS does the file opc-ua-local-discovery-server-1.04.402.461-20220210.zip you offer on the opcfoundation.org page contain? 1.04.402 or 1.04.403
Is the issue #68 already fixed in this version?

When I go to the Archives tab on the opcfoundation.org page I can find 1.04.402.463 which is newer than the newest file in the downloads 1.04.402.461

I think it is generally a must have to avoid editing existing releases. In my opinion changing something in the code necessarily results in a new release version as otherwise it is unclear which code a certain version number contains. After updating OpenSSL to 1.1.1m there should have been released a new version (eg. 1.04.404) and not adapted an existing release.

My suggestion is the following:

- Updating changelog,txt to 1.04.404
- Tagging the respective release with a git tag named 1.04.404 and adding a release on github for this version
- Uploading this newest release to the opcfoundation homepage

What do you think?

Best regards

**Comment by erhardgrishaber** [comment]
@jopi2016 : The observation of the version number inconsistency is correct. The Server code was updated to v1.04.403 but he installer was not yet ready for the changes (so it remained v1.04.402). This is in progress of fixing (probably this week). The installer will also have the v1.04.403 and a Git tag will be created as well.

**Comment by erhardgrishaber** [comment]
UA-LDS v1.04.403 is released.

**Comment by jopi2016** [comment]
@erhardgrishaber Thank you very much.
