### ISSUE TITLE
Currently only None, Basic128Rsa15 and Basic256 supported as SecurityPolicy?

### ISSUE THREAD

**Issue by jopi2016** [OPCFoundation/UA-LDS#72]
Hi,
I realized that at the moment only None, Basic128Rsa15 and Basic256 are supported as SecurityPolicy.
Are there plans to add newer SecurityPolicies as the above once are already deprecated?

Greetings

**Comment by erhardgrishaber** [comment]
@jopi2016 Newer security policies will be added & tested after the current release (v1.04.403)

**Comment by erhardgrishaber** [comment]
Fixed in UA-LDS v1.04.411
