### ISSUE TITLE
DiscoveryUrl in FindServersOnNetworkResponse not correct

### ISSUE THREAD

**Issue by MatthiasIsele** [OPCFoundation/UA-LDS#74]
1) Registers server at LDS with RegisterServer2Request and [0]: DiscoveryUrls: opc.tcp://[FE80::C428:8880:F2EF:D81C%8]:48010
2) Client calls FindServersOnNetwork on LDS and gets back DiscoveryUrl: opc.tcp://[FE80::C428:8880:F2EF:D81C%8].local.:48010

That is not a valid url. The LDS should only attach the .local string to a hostname but never to an IP address (IPv4 or IPv6).

**Comment by z-krejsa** [comment]
Is there any estimation when this bug will be fixed and the new version will be released?

**Comment by erhardgrishaber** [comment]
Fixed in UA-LDS v1.04.411
