### ISSUE TITLE
Mantis 3728: LDS doesnt refresh its own certificate on computer rename

### ISSUE THREAD

**Issue by dk2129** [OPCFoundation/UA-LDS#8]
A OPC UA Server calls the method StandardServer.RegistrationValidator_CertificateValidation() when registering with the LDS. If the computers hostname changed (for example by renaming it) without deleting the LDSs own certificates the OPC UA Server cannot register with the LDS as the domain in the LDS certificate doesn't match the machines hostname.

I don't know if this is expected behaviour. I think the LDS should check its own certificate on startup and replace it if necessary.
  
Steps to reproduce:
1. Install and start LDS
2. Rename computer
3. No server can register

**Comment by dk2129** [comment]
Current workaround:
Re-install the LDS.

**Comment by sorintopan** [comment]
Instructions were added to ualds.ini
# On machine name change, the own certificate should be re-created by uninstalling/reinstalling LDS OR by deleting the actual certificate and restarting the service
