### ISSUE TITLE
Compilable for linux?

### ISSUE THREAD

**Issue by Stasik0** [OPCFoundation/UA-LDS#9]
Hey,

is there any way to compile LDS-ME for linux?

Best Regards

**Comment by dk2129** [comment]
In general, the LDS-ME has been built for platform independence. Specifically this was the reason to develop it in AnsiC.
The OPC Foundation does not (does not plan to) provide a Linux version. The main reason is that most OPC UA Servers on Linux are embedded implementations where you only have a single UA application and will not need an LDS (the UA application itself will use port 4840.
Many Linux versions already include mDNS and the "ME (multicast)" portion of the LDS-ME will have to be re-developed for Linux.

**Comment by eoursel** [comment]
Hi Karl. 

The point is that it would be nice to have a linux version to build a docker image even without mDNS.  We are running Netcore OPC UA servers inside docker containers but we are missing the LDS part.

**Comment by erhardgrishaber** [comment]
Fixed in LDS v.1.03.370
